{
	"CreateLinks": [],
	"OnFailure": "/MyCanteen01/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/MyCanteen01/Actions/CreateEntitySuccessMessage.action",
	"Properties": {
	"CanteenID": "#Control:CanteenID/#Value",
	"Location": "#Control:Location/#Value",
	"Name": "#Control:Name/#Value"
},
	"Target": {
		"EntitySet": "CanteenSet",
		"Service": "/MyCanteen01/Services/MyCanteen01Ser.service"
	},
	"ActionResult": {
		"_Name": "create"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}