{
	"CreateLinks": [],
	"OnFailure": "/MyCanteen01/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/MyCanteen01/Actions/CreateEntitySuccessMessage.action",
	"Properties": {
	"BookingID": "#Control:BookingID/#Value",
	"CanteenID": "#Control:CanteenID/#Value",
	"Dessert": "#Control:Dessert/#Value",
	"MainDish": "#Control:MainDish/#Value",
	"MenuID": "#Control:MenuID/#Value",
	"Price": "#Control:Price/#Value",
	"Sides": "#Control:Sides/#Value",
	"Soup": "#Control:Soup/#Value",
	"dateOfLunch": "#Control:dateOfLunch/#Value",
	"kcalForMain": "#Control:kcalForMain/#Value",
	"veggie": "#Control:veggie/#Value"
},
	"Target": {
		"EntitySet": "MenuSet",
		"Service": "/MyCanteen01/Services/MyCanteen01Ser.service"
	},
	"ActionResult": {
		"_Name": "create"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}