{
	"Animated": true,
	"Duration": 2,
	"Message": "Entity updated",
	"Icon": "",
	"IsIconHidden": false,
	"NumberOfLines": 2,
	"OnSuccess": "/MyCanteen01/Actions/CloseModalPage_Complete.action",
	"_Type": "Action.Type.ToastMessage"
}